# Base Config
permalink: /:categories/:title.html
highlighter: pygments
# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough","with_toc_data"]
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
#   use_coderay: true
#   syntax_highlighter: rouge
#   coderay:
#     coderay_line_numbers:  nil

# Site config
title: curly's blog
author: curly Cheng
img_dir: /images

# Blog-Nav config
blog-nav:
  - text: Timeline
    url: /index.html
  - text: Categories 
    url: /categories.html
  - text: Archives
    url: /archives.html
  - text: Tags
    url: /tags.html
  - text: Projects
    url: /projects.html

# Site-nav config
site-nav:
  - text: Blog
    url: /index.html
  - text: Paint 
    url: /paint.html
  - text: Write
    url: /write.html
  - text: About
    url: /about.html





